const list = [
    {
      title: "Orange",
      img: "/src/products/fruit-1.jpeg",
      price: "$5.50",
      type: "Appetizers/Starters",
    },
    {
      title: "Tangerine",
      img: "/src/products/fruit-2.jpeg",
      price: "$3.00",
      type: "Appetizers/Starters",
    },
    {
      title: "Raspberry",
      img: "/src/products/fruit-3.jpeg",
      price: "$10.00",
      type: "Main Courses/Entrees",
    },
    {
      title: "Lemon",
      img: "/src/products/fruit-4.jpeg",
      price: "$5.30",
      type: "Main Courses/Entrees",
    },
    {
      title: "Avocado",
      img: "/src/products/fruit-5.jpeg",
      price: "$15.70",
      type: "Desserts",
    },
    {
      title: "Lemon 2",
      img: "/src/products/fruit-6.jpeg",
      price: "$8.00",
      type: "Desserts",
    },
    {
      title: "Banana",
      img: "/src/products/fruit-7.jpeg",
      price: "$7.50",
      type: "Beverages/Drinks",
    },
    {
      title: "Watermelon",
      img: "/src/products/fruit-8.jpeg",
      price: "$12.20",
      type: "Beverages/Drinks",
    },
    {
      title: "Orange",
      img: "/src/products/fruit-1.jpeg",
      price: "$5.50",
      type: "Appetizers/Starters",
    },
    {
      title: "Tangerine",
      img: "/src/products/fruit-2.jpeg",
      price: "$3.00",
      type: "Appetizers/Starters",
    },
    {
      title: "Raspberry",
      img: "/src/products/fruit-3.jpeg",
      price: "$10.00",
      type: "Main Courses/Entrees",
    },
    {
      title: "Lemon",
      img: "/src/products/fruit-4.jpeg",
      price: "$5.30",
      type: "Main Courses/Entrees",
    },
    {
      title: "Avocado",
      img: "/src/products/fruit-5.jpeg",
      price: "$15.70",
      type: "Desserts",
    },
    {
      title: "Lemon 2",
      img: "/src/products/fruit-6.jpeg",
      price: "$8.00",
      type: "Desserts",
    },
    {
      title: "Banana",
      img: "/src/products/fruit-7.jpeg",
      price: "$7.50",
      type: "Beverages/Drinks",
    },
    {
      title: "Watermelon",
      img: "/src/products/fruit-8.jpeg",
      price: "$12.20",
      type: "Beverages/Drinks",
    },
    {
      title: "Orange",
      img: "/src/products/fruit-1.jpeg",
      price: "$5.50",
      type: "Appetizers/Starters",
    },
    {
      title: "Tangerine",
      img: "/src/products/fruit-2.jpeg",
      price: "$3.00",
      type: "Appetizers/Starters",
    },
    {
      title: "Raspberry",
      img: "/src/products/fruit-3.jpeg",
      price: "$10.00",
      type: "Main Courses/Entrees",
    },
    {
      title: "Lemon",
      img: "/src/products/fruit-4.jpeg",
      price: "$5.30",
      type: "Main Courses/Entrees",
    },
    {
      title: "Avocado",
      img: "/src/products/fruit-5.jpeg",
      price: "$15.70",
      type: "Desserts",
    },
    {
      title: "Lemon 2",
      img: "/src/products/fruit-6.jpeg",
      price: "$8.00",
      type: "Desserts",
    },
    {
      title: "Banana",
      img: "/src/products/fruit-7.jpeg",
      price: "$7.50",
      type: "Beverages/Drinks",
    },
    {
      title: "Watermelon",
      img: "/src/products/fruit-8.jpeg",
      price: "$12.20",
      type: "Beverages/Drinks",
    },
    {
      title: "Orange",
      img: "/src/products/fruit-1.jpeg",
      price: "$5.50",
      type: "Appetizers/Starters",
    },
    {
      title: "Tangerine",
      img: "/src/products/fruit-2.jpeg",
      price: "$3.00",
      type: "Appetizers/Starters",
    },
    {
      title: "Raspberry",
      img: "/src/products/fruit-3.jpeg",
      price: "$10.00",
      type: "Main Courses/Entrees",
    },
    {
      title: "Lemon",
      img: "/src/products/fruit-4.jpeg",
      price: "$5.30",
      type: "Main Courses/Entrees",
    },
    {
      title: "Avocado",
      img: "/src/products/fruit-5.jpeg",
      price: "$15.70",
      type: "Desserts",
    },
    {
      title: "Lemon 2",
      img: "/src/products/fruit-6.jpeg",
      price: "$8.00",
      type: "Desserts",
    },
    {
      title: "Banana",
      img: "/src/products/fruit-7.jpeg",
      price: "$7.50",
      type: "Beverages/Drinks",
    },
    {
      title: "Watermelon",
      img: "/src/products/fruit-8.jpeg",
      price: "$12.20",
      type: "Beverages/Drinks",
    },
  ];

export default list;